# SwiftLint Configuration for Forgetze
# This configuration is tailored for the Forgetze iOS app

# Paths to include/exclude
included:
  - Forgetze/Forgetze
  - Forgetze/ForgetzeTests
  - Forgetze/ForgetzeUITests

excluded:
  - Forgetze/Forgetze/Preview Content
  - Forgetze/Forgetze/Assets.xcassets
  - Forgetze/Forgetze/Icon-*.png
  - Forgetze/Forgetze/Forgetze.entitlements
  - Forgetze/Forgetze/Info.plist

# Rules to disable (based on common iOS development patterns)
disabled_rules:
  - trailing_whitespace  # Xcode handles this automatically
  - todo                # Allow TODO comments for development
  - line_length         # We'll set custom limits below

# Custom rule configurations
line_length:
  warning: 120
  error: 150
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

identifier_name:
  min_length: 2
  max_length: 40
  excluded:
    - id
    - url
    - api
    - ui
    - db
    - ok
    - no

type_name:
  min_length: 3
  max_length: 40

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 6
  error: 8

file_length:
  warning: 400
  error: 600

type_body_length:
  warning: 200
  error: 400

cyclomatic_complexity:
  warning: 10
  error: 20

nesting:
  type_level:
    warning: 3
    error: 5
  statement_level:
    warning: 5
    error: 8

# SwiftUI specific rules
closure_body_length:
  warning: 30
  error: 50

# Force unwrapping rules (important for safety)
force_unwrapping:
  severity: warning

# Implicitly unwrapped optionals
implicitly_unwrapped_optional:
  severity: warning

# Force casting
force_cast:
  severity: warning

# Force try
force_try:
  severity: warning

# Empty count (use isEmpty instead)
empty_count:
  severity: warning

# Prefer isEmpty over count == 0
empty_count:
  severity: warning

# Prefer guard over if-let
guard_else:
  severity: warning

# Prefer early return
early_return:
  severity: warning

# Unused imports
unused_import:
  severity: warning

# Unused variables
unused_private_declaration:
  severity: warning

# Dead code
dead_code:
  severity: warning

# SwiftUI specific
closure_end_indentation:
  severity: warning

# Documentation
missing_docs:
  severity: warning
  excludes:
    - Forgetze/Forgetze/Preview Content
    - Forgetze/ForgetzeTests
    - Forgetze/ForgetzeUITests

# Custom rules for Forgetze
custom_rules:
  # Ensure proper error handling
  proper_error_handling:
    name: "Proper Error Handling"
    regex: 'fatalError\('
    message: "Avoid fatalError in production code. Use proper error handling instead."
    severity: warning

  # Ensure proper memory management
  memory_management:
    name: "Memory Management"
    regex: 'weak self'
    message: "Good use of weak self for memory management"
    severity: info

# Reporter type
reporter: "xcode"

# Analyzer rules (if using SwiftLint with analyzer)
analyzer_rules:
  - explicit_self
  - unused_declaration
  - unused_import
  - unused_private_declaration
